version: '3.9'

services:
  hajj-db-dev-2:
    image: postgres:14.5
    container_name: hajj-db-dev-2
    restart: unless-stopped
    command: postgres -c 'max_connections=500'
    ports:
      - "7074:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password1
      - POSTGRES_USER=user1
      - POSTGRES_DB=db1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user1 -d db1"]
      interval: 10s
      timeout: 5s
      retries: 5

# jdbc:postgresql://localhost:7074/db1?user=user1&password=password1

# sudo docker compose -f db-compose.yml down
# sudo docker compose -f db-compose.yml up -d


