@HajjSystem_Webapi_HostAddress = http://localhost:5116

# User API

### Create Customer User
POST {{HajjSystem_Webapi_HostAddress}}/api/user/customer
Content-Type: application/json

{
  "firstName": "Ahmed",
  "middleName": "Mohammed",
  "lastName": "Ali",
  "username": "ahmed.ali",
  "password": "SecurePassword123",
  "email": "ahmed.ali@example.com",
  "seasonId": 1
}

### Create Company User
POST {{HajjSystem_Webapi_HostAddress}}/api/user/company
Content-Type: application/json

{
  "firstName": "Fatima",
  "middleName": "Hassan",
  "lastName": "Ibrahim",
  "username": "fatima.company",
  "password": "CompanyPass456",
  "email": "fatima@travelagency.com",
  "companyName": "Al-Rahma Travel Agency 5",
  "crNumber": "1234567895",
  "seasonId": 1
}
### Login User
POST {{HajjSystem_Webapi_HostAddress}}/api/user/login
Content-Type: application/json

{
  "username": "ahmed.ali",
  "password": "SecurePassword123"
}
###
